name: Build Windows
on: [workflow_call, workflow_dispatch]
jobs:
  buildWindows:
    name: Build Windows
    strategy:
      matrix:
        buildPlatform:
          # unity-builder fails on windows-2022 (https://github.com/game-ci/unity-builder/issues/542)
          - windows-2019 # build on windows to support Unity IL2CPP scripting backend
        targetPlatform:
          - StandaloneWindows64
        architecture:
          - x64 # Intel 64-bit
          - x86 # Intel 32-bit
          - ARM64 # ARM 64-bit
    uses: ./.github/workflows/build_unity.yml
    with:
      buildName: Windows-${{ matrix.architecture }}
      buildPlatform: ${{ matrix.buildPlatform }}
      targetPlatform: ${{ matrix.targetPlatform }}
      customParameters: -architecture ${{ matrix.architecture }}
    secrets:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
