name: Build macOS
on: [workflow_dispatch, workflow_call]
jobs:
  buildMacOS:
    name: Build for MacOS
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targetPlatform:
          - StandaloneOSX
        architecture:
          - x64 # Intel 64-bit
          - ARM64 # Apple silicon
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ${{ vars.UNITY_PROJECT_PATH }}/Library
          key: Library-${{ vars.UNITY_PROJECT_PATH }}-${{ matrix.targetPlatform }}-${{ hashFiles(vars.UNITY_PROJECT_PATH) }}
          restore-keys: |
            Library-${{ vars.UNITY_PROJECT_PATH }}-${{ matrix.targetPlatform }}-
            Library-${{ vars.UNITY_PROJECT_PATH }}-
            Library-
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: ${{ vars.UNITY_PROJECT_PATH }}
          targetPlatform: ${{ matrix.targetPlatform }}
          buildMethod: UnityBuilderAction.Builder.BuildProject
          customParameters: -architecture ${{ matrix.architecture }}
      - uses: actions/upload-artifact@v3
        with:
          name: MacOS Build
          path: build
