name: Build macOS (IL2CPP)
on: [workflow_call, workflow_dispatch]
jobs:
  buildWindows:
    name: Build macOS (IL2CPP)
    strategy:
      matrix:
        buildPlatform:
          - macos-latest
        targetPlatform:
          - StandaloneOSX
        architecture:
          - x64 # Intel 64-bit
          - ARM64 # Apple silicon
    uses: ./.github/workflows/build_unity.yml
    with:
      buildName: macOS-${{ matrix.architecture }}-IL2CPP
      buildPlatform: ${{ matrix.buildPlatform }}
      targetPlatform: ${{ matrix.targetPlatform }}
      customParameters: -architecture ${{ matrix.architecture }}
    secrets:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
